#!/bin/bash
source $HOME/.cache/wal/colors.sh

BATSTAT=$(acpi | sed 's/,//g; s/Charging/++/; s/Discharging/dis/; s/Unknown//; s/:[0-9]* / /g' | awk '{print $4" "$3" ("$5")"}')
STAT=$(echo $BATSTAT | awk '{print $2}')
PERC=$(echo $BATSTAT | grep '^[0-9]*' -o)

BATSTAT=$(echo $BATSTAT | sed 'N;s/\n/ /')

case $PERC in
    9[0-9] | 100)
        echo "<span color='$color2'>$BATSTAT</span>"
        ;;
    2[0-5])
        echo "<span color='$color3'>$BATSTAT</span>"
        ;;
    1[0-9])
        echo "<span color='$color1'>$BATSTAT</span>"
        ;;
    [0-9])
        if [[ "$STAT" == "dis" ]]; then
            echo "<span bgcolor='red' color='black'>$BATSTAT</span>"
        else
            echo "<span color='$color1'>$BATSTAT</span>"
        fi
        ;;
    *)
        echo $BATSTAT
esac
