#!/bin/bash
# Get colors
source $HOME/.cache/wal/colors.sh
# Fully loaded in mWh
bat0_energy_full=$(cat /sys/class/power_supply/BAT0/energy_full)
bat1_energy_full=$(cat /sys/class/power_supply/BAT1/energy_full)

# Currently loaded in mWh
bat0_energy_now=$(cat /sys/class/power_supply/BAT0/energy_now)
bat1_energy_now=$(cat /sys/class/power_supply/BAT1/energy_now)

# Charge/Discharge rate in mW
bat0_power_now=$(cat /sys/class/power_supply/BAT0/power_now)
bat1_power_now=$(cat /sys/class/power_supply/BAT1/power_now)

# Charge/Discharge status placeholders
bat0_status=$(cat /sys/class/power_supply/BAT0/status | \
    awk '/Charging/ {printf "++"}; /Discharging/ {printf "--"}; /Unknown/ {printf ""}')
bat1_status=$(cat /sys/class/power_supply/BAT1/status | \
    awk '/Charging/ {printf "++"}; /Discharging/ {printf "--"}; /Unknown/ {printf ""}')

# Current capacity in percent
bat0_perc=$(echo "100 * ${bat0_energy_now} / ${bat0_energy_full}" | bc)
bat1_perc=$(echo "100 * ${bat1_energy_now} / ${bat1_energy_full}" | bc)

# Time to full/empty
if [[ ${bat0_status} == "++" ]]; then
    bat0_time=$(echo "60 * (${bat0_energy_full} - ${bat0_energy_now}) / ${bat0_power_now}" | bc)
else  # [[ ${bat0_status} == "--" ]]
    bat0_time=$(echo "60 * ${bat0_energy_now} / ${bat0_power_now}" | bc)
fi
if [[ ${bat1_status} == "++" ]]; then
    bat1_time=$(echo "60 * (${bat1_energy_full} - ${bat1_energy_now}) / ${bat1_power_now}" | bc)
else  # [[ ${bat0_status} == "--" ]]
    bat1_time=$(echo "60 * ${bat1_energy_now} / ${bat1_power_now}" | bc)
fi

# Generate output
output_0="${bat0_perc}% (${bat0_time}m) ${bat0_status}"
output_1="${bat1_perc}% (${bat1_time}m) ${bat1_status}"

# Colorize output
case $bat0_perc in
    9[0-9] | 100)
        colored_0="<span color='$color2'>${output_0}</span>" ;;
    2[0-5])
        colored_0="<span color='$color3'>${output_0}</span>" ;;
    1[0-9])
        colored_0="<span color='$color1'>${output_0}</span>" ;;
    [0-9])
        if [[ "$bat0_status" == "--" ]]; then
            colored_0="<span bgcolor='red' color='black'>${output_0}</span>"
        else
            colored_0="<span color='$color1'>${output_0}</span>"
        fi ;;
    *)
        colored_0=${output_0}
esac
case $bat1_perc in
    9[0-9] | 100)
        colored_1="<span color='$color2'>${output_1}</span>" ;;
    2[0-5])
        colored_1="<span color='$color3'>${output_1}</span>" ;;
    1[0-9])
        colored_1="<span color='$color1'>${output_1}</span>" ;;
    [0-9])
        if [[ "$bat1_status" == "--" ]]; then
            colored_1="<span bgcolor='red' color='black'>${output_1}</span>"
        else
            colored_1="<span color='$color1'>${output_1}</span>"
        fi ;;
    *)
        colored_1=${output_1}
esac

# Output information
echo "${colored_0} ${colored_1}"
