#!/bin/bash
# vim: ft=sh
DRPBX_CMD="dropbox-cli"
source ~/.cache/wal/colors.sh
d=$("$DRPBX_CMD" status)

case "$d" in
    "Dropbox isn't running!")
        echo "<span foreground='$color1'>Dropbox</span>"
        ;;
    "Up to date")
        echo "<span foreground='$color2'>$d</span>"
        ;;
    *)
        echo "<span foreground='$color3'>$d</span>"
        ;;
esac


# if [[ "$d" == "Dropbox isn't running!" ]]; then
#     echo "<span foreground='$color1'>$d</span>"
# elif [[ "$d" == "Up to date" ]]; then
#     echo "<span foreground='$color2'>$d</span>"
# else
#     echo "<span foreground='$color3'>$d</span>"
# fi

# case $BLOCK_BUTTON in
#     1) dropbox start;;
#     3) dropbox stop;;
# esac
