#!/bin/bash
# vim: ft=sh


FREEMEM=$(free --mega | awk '/Mem/ {print $3, $2}')
ABSMEM=$(echo "$FREEMEM" | awk '{print $1}')
RELMEM=$(echo "$FREEMEM" | awk '{print $1 "/" $2 "*100"}' | bc -l | grep -E '.*\..' -o)

FREESWP=$(free --mega | awk '/Swap/ {print $3, $2}')
ABSSWP=$(echo "$FREESWP" | awk '{print $1}')
RELSWP=$(echo "$FREESWP" | awk '{print $1 "/" $2 "*100"}' | bc -l | grep -E '.*\..' -o)

if [[ "$ABSSWP" == 0 ]]; then
    echo "${ABSMEM}M ${RELMEM}%"
else
    echo "${ABSMEM}M ${RELMEM}%; ${ABSSWP}M ${RELSWP}%"
fi
