#!/usr/bin/env python
# vim:ft=py
import numpy as np

def function(a, b):
    r = a**2 + b**2
    s = np.sqrt(r)
    return np.round(s, 2)

if __name__ == '__main__':
    a = np.random.rand()
    b = np.random.randint(10)
    print(function(a, b))
