#!/bin/bash
# vim: ft=sh
# source $HOME/.cache/wal/colors.sh
# traffic=$(curl -s gateway.engel/traffic.php | awk '/bleiben noch/ {print $42}')

# if [[ "$traffic" > "6000" ]]; then
#     echo "<span foreground='$color2'>$traffic MB</span>"
# elif [[ "$traffic" > "2000" ]]; then
#     echo "<span foreground='$color3'>$traffic MB</span>"
# else
#     echo "<span foreground='$color1'>$traffic MB</span>"
# fi

# echo $traffic" MB"

curl -s gateway.engel/traffic.php | awk '/bleiben noch/ {print $42" MB"}'
