#!/bin/bash
AUR_UPDATES=$(cower -u | wc -l)
ARCH_UPDATES=$(checkupdates | wc -l)

UPDATES=$(echo $ARCH_UPDATES+$AUR_UPDATES | bc)

case $UPDATES in
    0) ;;
    *) echo " $ARCH_UPDATES+$AUR_UPDATES" ;;
esac
