#!/bin/bash
AUR_UPDATES=$(cower -u | awk 'END {print NR}')
ARCH_UPDATES=$(checkupdates | awk 'END {print NR}')

UPDATES=$(echo $ARCH_UPDATES+$AUR_UPDATES | bc)

case $UPDATES in
    [5-9][0-9]) echo " $ARCH_UPDATES+$AUR_UPDATES" ;;
    *) ;;
esac
