#!/bin/sh
# vim:ft=sh
case $1 in
    period-changed)
        if [[ "$3" == "night" ]]; then
            ~/miniconda3/bin/wal -f ~/.google_dark.json -q
        elif [[  "$3" == "daytime" ]]; then
            ~/miniconda3/bin/wal -f ~/.google_light.json -q
        fi
esac
