#!/bin/sh
# vim:ft=sh
function change_vimrc {
    if [[ "$1" == "night" ]]; then
        new_colorscheme=nord
        old_colorscheme=wal
        new_background=dark
        old_background=light
    elif [[ "$1" == "daytime" ]]; then
        new_colorscheme=wal
        old_colorscheme=nord
        new_background=light
        old_background=dark
    fi
    sed -i "s/colorscheme $old_colorscheme/colorscheme $new_colorscheme/" ~/.vimrc
    sed -i "s/background=$old_background/background=$new_background/" ~/.vimrc
}

# case $1 in
#     period-changed)
#         if [[ "$3" == "night" ]]; then
#             ~/miniconda3/bin/wal -q -f ~/.nord.json
#             change_vimrc $3
#         elif [[  "$3" == "daytime" ]]; then
#             ~/miniconda3/bin/wal -q -f ~/.google_light.json
#             change_vimrc $3
#         fi
# esac
