#!/bin/bash
# vim: ft=sh
source $HOME/.cache/wal/colors.sh
traffic=$(curl -s gateway.engel/traffic.php | grep "bleiben noch....: [0-9]* MegaBytes" -o | sed s/MegaBytes/MB/ | grep "[0-9]*" -o)

if [[ "$traffic" > "6000" ]]; then
    echo "<span foreground='$color2'>$traffic MB</span>"
elif [[ "$traffic" > "2000" ]]; then
    echo "<span foreground='$color3'>$traffic MB</span>"
else
    echo "<span foreground='$color1'>$traffic MB</span>"
fi
