#!/bin/bash
# vim: ft=sh

# echo Hallo $BLOCK_BUTTON

case $BLOCK_BUTTON in
    1) xautolock -disable; echo "&#xf0f4;" ;;
    3) xautolock -enable; echo "&#xf0fc;" ;;
    *) xautolock -enable; echo "&#xf0fc;" ;;
esac
