#!/bin/bash
# vim: ft=sh
connection=$(nmcli | grep 'connected' | sed 's/[0-9a-z]*:\ disconnected/disconnected/' | sed 's/[a-z0-9]*:\ connected\ to\ //' | sed ':a;N;s/\n/\, /g')

disconnected=$(echo $connection | grep 'disconnected')

if [[ "$disconnected" == "disconnected" ]]; then
    echo "<span foreground='#BF616A'>$connection</span>"
elif [[ "$disconnected" == "$connection" ]]; then
    echo "<span foreground='#EBCB8B'>$connection</span>"
else
    echo "<span foreground='#A3BE8C'>$connection</span>"
fi
