#!/bin/bash
# vim: ft=sh
N=4
myping=$(ping duckduckgo.com -c$N)
stats=$(echo "$myping" | grep 'transmitted')
rtttime=$(echo "$myping"  | grep 'rtt')

received=$(echo "$stats" | grep '[0-4]\ received' -o | grep '[0-4]' -o)

min_avg_max=$(echo "$rtttime" | grep '[0-9]*\.[0-9]*\/[0-9]*\.[0-9]*\/[0-9]*\.[0-9]*\/[0-9]*\.[0-9]*' -o)
# echo "$received received"

if [[ "$received" == "$N" ]]; then
    echo "<span foreground='#A3BE8C'>$min_avg_max</span>"
else
    echo "<span foreground='#BF616A'>error</span>"
fi
