#!/bin/bash
# vim: ft=sh
source $HOME/.config/i3blocks/scripts/colors

minutes=$(uptime -p | grep '[0-9]*\ minute[s]*' -o | grep '[0-9]*' -o)
m="$minutes"m
hours=$(uptime -p | grep '[0-9]*\ hour[s]*' -o | grep '[0-9]*' -o)
h="$hours"h
days=$(uptime -p | grep '[0-9]*\ day[s]*' -o | grep '[0-9]*' -o)
d="$days"d

if [[ "$days" > "0" ]]; then
    echo "<span foreground='$red'>$d $h:$m</span>"
elif [[ "$hours" > "4" ]]; then
    echo "<span foreground='$red'>$h:$m</span>"
elif [[ "$hours" > "2" ]]; then
    echo "<span foreground='$yellow'>$h:$m</span>"
elif [[ "$hours" < "1" ]]; then
    echo "<span foreground='$green'>$m</span>"
else
    echo "<span foreground='$green'>$h:$m</span>"
fi
